Remove `propertyIsEnumerable()`
sindresorhus/filter-obj pull request #26
Opened 2022-07-27 14:34 UTC by ehmicky

Inspired by https://github.com/sindresorhus/filter-obj/issues/24

This is a small refactoring that uses `Object.getOwnPropertyDescriptor().enumerable` instead of `Object.prototype.propertyIsEnumerable()`. It does not change the behavior, but yields a small performance boost.

The following table shows a comparison before and after this PR. Each row uses an object with a different amount of properties. The cells are the mean duration per property.

```js
Function predicate:
                 Before  After
1 property:      408ns   378ns       
10 properties:   184ns   176ns       
1e2 properties:  257ns   209ns       
1e3 properties:  439ns   386ns       
1e4 properties:  325ns   310ns       
1e5 properties:  394ns   383ns       
1e6 properties:  741ns   737ns       

Array with 100 keys:
                 Before  After
1 property:      308ns   298ns       
10 properties:    59ns    57ns       
1e2 properties:   45ns    38ns       
1e3 properties:   20ns     9ns       
1e4 properties:   20ns    17ns       
1e5 properties:   26ns    22ns       
1e6 properties:   64ns    55ns       
```

2022-07-27 21:58 UTC, sindresorhus commented
Can you fix the merge conflict?

2022-07-28 13:10 UTC, ehmicky commented
Fixed :+1:

2022-07-29 23:32 UTC, sindresorhus requested changes

2022-07-29 23:32 UTC, sindresorhus commented on index.js
> +			if (descriptor !== undefined && descriptor.enumerable) {
```suggestion
			const descriptor = Object.getOwnPropertyDescriptor(object, key);
			if (descriptor?.enumerable) {
```

2022-07-30 18:00 UTC, merged